//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class DetectionValidator : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DetectionValidator(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DetectionValidator obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~DetectionValidator() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LaandmrkDetectorPINVOKE.delete_DetectionValidator(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public int validator_type {
    set {
      LaandmrkDetectorPINVOKE.DetectionValidator_validator_type_set(swigCPtr, value);
    } 
    get {
      int ret = LaandmrkDetectorPINVOKE.DetectionValidator_validator_type_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_std__vectorT_cv__Vec3d_t orientations {
    set {
      LaandmrkDetectorPINVOKE.DetectionValidator_orientations_set(swigCPtr, SWIGTYPE_p_std__vectorT_cv__Vec3d_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LaandmrkDetectorPINVOKE.DetectionValidator_orientations_get(swigCPtr);
      SWIGTYPE_p_std__vectorT_cv__Vec3d_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_std__vectorT_cv__Vec3d_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_std__vectorT_PAW_t paws {
    set {
      LaandmrkDetectorPINVOKE.DetectionValidator_paws_set(swigCPtr, SWIGTYPE_p_std__vectorT_PAW_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LaandmrkDetectorPINVOKE.DetectionValidator_paws_get(swigCPtr);
      SWIGTYPE_p_std__vectorT_PAW_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_std__vectorT_PAW_t(cPtr, false);
      return ret;
    } 
  }

  public Double_List bs {
    set {
      LaandmrkDetectorPINVOKE.DetectionValidator_bs_set(swigCPtr, Double_List.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LaandmrkDetectorPINVOKE.DetectionValidator_bs_get(swigCPtr);
      Double_List ret = (cPtr == global::System.IntPtr.Zero) ? null : new Double_List(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_std__vectorT_cv__Mat_T_double_t_t ws {
    set {
      LaandmrkDetectorPINVOKE.DetectionValidator_ws_set(swigCPtr, SWIGTYPE_p_std__vectorT_cv__Mat_T_double_t_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LaandmrkDetectorPINVOKE.DetectionValidator_ws_get(swigCPtr);
      SWIGTYPE_p_std__vectorT_cv__Mat_T_double_t_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_std__vectorT_cv__Mat_T_double_t_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_std__vectorT_std__vectorT_cv__Mat_T_double_t_t_t ws_nn {
    set {
      LaandmrkDetectorPINVOKE.DetectionValidator_ws_nn_set(swigCPtr, SWIGTYPE_p_std__vectorT_std__vectorT_cv__Mat_T_double_t_t_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LaandmrkDetectorPINVOKE.DetectionValidator_ws_nn_get(swigCPtr);
      SWIGTYPE_p_std__vectorT_std__vectorT_cv__Mat_T_double_t_t_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_std__vectorT_std__vectorT_cv__Mat_T_double_t_t_t(cPtr, false);
      return ret;
    } 
  }

  public Int_List activation_fun {
    set {
      LaandmrkDetectorPINVOKE.DetectionValidator_activation_fun_set(swigCPtr, Int_List.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LaandmrkDetectorPINVOKE.DetectionValidator_activation_fun_get(swigCPtr);
      Int_List ret = (cPtr == global::System.IntPtr.Zero) ? null : new Int_List(cPtr, false);
      return ret;
    } 
  }

  public Int_List output_fun {
    set {
      LaandmrkDetectorPINVOKE.DetectionValidator_output_fun_set(swigCPtr, Int_List.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LaandmrkDetectorPINVOKE.DetectionValidator_output_fun_get(swigCPtr);
      Int_List ret = (cPtr == global::System.IntPtr.Zero) ? null : new Int_List(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_std__vectorT_std__vectorT_std__vectorT_std__vectorT_cv__Mat_T_float_t_t_t_t_t cnn_convolutional_layers {
    set {
      LaandmrkDetectorPINVOKE.DetectionValidator_cnn_convolutional_layers_set(swigCPtr, SWIGTYPE_p_std__vectorT_std__vectorT_std__vectorT_std__vectorT_cv__Mat_T_float_t_t_t_t_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LaandmrkDetectorPINVOKE.DetectionValidator_cnn_convolutional_layers_get(swigCPtr);
      SWIGTYPE_p_std__vectorT_std__vectorT_std__vectorT_std__vectorT_cv__Mat_T_float_t_t_t_t_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_std__vectorT_std__vectorT_std__vectorT_std__vectorT_cv__Mat_T_float_t_t_t_t_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_std__vectorT_std__vectorT_std__vectorT_std__vectorT_std__pairT_int_cv__Mat_T_double_t_t_t_t_t_t cnn_convolutional_layers_dft {
    set {
      LaandmrkDetectorPINVOKE.DetectionValidator_cnn_convolutional_layers_dft_set(swigCPtr, SWIGTYPE_p_std__vectorT_std__vectorT_std__vectorT_std__vectorT_std__pairT_int_cv__Mat_T_double_t_t_t_t_t_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LaandmrkDetectorPINVOKE.DetectionValidator_cnn_convolutional_layers_dft_get(swigCPtr);
      SWIGTYPE_p_std__vectorT_std__vectorT_std__vectorT_std__vectorT_std__pairT_int_cv__Mat_T_double_t_t_t_t_t_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_std__vectorT_std__vectorT_std__vectorT_std__vectorT_std__pairT_int_cv__Mat_T_double_t_t_t_t_t_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_std__vectorT_std__vectorT_std__vectorT_float_t_t_t cnn_convolutional_layers_bias {
    set {
      LaandmrkDetectorPINVOKE.DetectionValidator_cnn_convolutional_layers_bias_set(swigCPtr, SWIGTYPE_p_std__vectorT_std__vectorT_std__vectorT_float_t_t_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LaandmrkDetectorPINVOKE.DetectionValidator_cnn_convolutional_layers_bias_get(swigCPtr);
      SWIGTYPE_p_std__vectorT_std__vectorT_std__vectorT_float_t_t_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_std__vectorT_std__vectorT_std__vectorT_float_t_t_t(cPtr, false);
      return ret;
    } 
  }

  public Int_List2N cnn_subsampling_layers {
    set {
      LaandmrkDetectorPINVOKE.DetectionValidator_cnn_subsampling_layers_set(swigCPtr, Int_List2N.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LaandmrkDetectorPINVOKE.DetectionValidator_cnn_subsampling_layers_get(swigCPtr);
      Int_List2N ret = (cPtr == global::System.IntPtr.Zero) ? null : new Int_List2N(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_std__vectorT_std__vectorT_cv__Mat_T_float_t_t_t cnn_fully_connected_layers_weights {
    set {
      LaandmrkDetectorPINVOKE.DetectionValidator_cnn_fully_connected_layers_weights_set(swigCPtr, SWIGTYPE_p_std__vectorT_std__vectorT_cv__Mat_T_float_t_t_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LaandmrkDetectorPINVOKE.DetectionValidator_cnn_fully_connected_layers_weights_get(swigCPtr);
      SWIGTYPE_p_std__vectorT_std__vectorT_cv__Mat_T_float_t_t_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_std__vectorT_std__vectorT_cv__Mat_T_float_t_t_t(cPtr, false);
      return ret;
    } 
  }

  public Float_List2N cnn_fully_connected_layers_bias {
    set {
      LaandmrkDetectorPINVOKE.DetectionValidator_cnn_fully_connected_layers_bias_set(swigCPtr, Float_List2N.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LaandmrkDetectorPINVOKE.DetectionValidator_cnn_fully_connected_layers_bias_get(swigCPtr);
      Float_List2N ret = (cPtr == global::System.IntPtr.Zero) ? null : new Float_List2N(cPtr, false);
      return ret;
    } 
  }

  public Int_List2N cnn_layer_types {
    set {
      LaandmrkDetectorPINVOKE.DetectionValidator_cnn_layer_types_set(swigCPtr, Int_List2N.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LaandmrkDetectorPINVOKE.DetectionValidator_cnn_layer_types_get(swigCPtr);
      Int_List2N ret = (cPtr == global::System.IntPtr.Zero) ? null : new Int_List2N(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_std__vectorT_std__vectorT_cv__Mat_T_float_t_t_t cnn_fully_connected_layers_biases {
    set {
      LaandmrkDetectorPINVOKE.DetectionValidator_cnn_fully_connected_layers_biases_set(swigCPtr, SWIGTYPE_p_std__vectorT_std__vectorT_cv__Mat_T_float_t_t_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LaandmrkDetectorPINVOKE.DetectionValidator_cnn_fully_connected_layers_biases_get(swigCPtr);
      SWIGTYPE_p_std__vectorT_std__vectorT_cv__Mat_T_float_t_t_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_std__vectorT_std__vectorT_cv__Mat_T_float_t_t_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_std__vectorT_cv__Mat_T_double_t_t mean_images {
    set {
      LaandmrkDetectorPINVOKE.DetectionValidator_mean_images_set(swigCPtr, SWIGTYPE_p_std__vectorT_cv__Mat_T_double_t_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LaandmrkDetectorPINVOKE.DetectionValidator_mean_images_get(swigCPtr);
      SWIGTYPE_p_std__vectorT_cv__Mat_T_double_t_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_std__vectorT_cv__Mat_T_double_t_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_std__vectorT_cv__Mat_T_double_t_t standard_deviations {
    set {
      LaandmrkDetectorPINVOKE.DetectionValidator_standard_deviations_set(swigCPtr, SWIGTYPE_p_std__vectorT_cv__Mat_T_double_t_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LaandmrkDetectorPINVOKE.DetectionValidator_standard_deviations_get(swigCPtr);
      SWIGTYPE_p_std__vectorT_cv__Mat_T_double_t_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_std__vectorT_cv__Mat_T_double_t_t(cPtr, false);
      return ret;
    } 
  }

  public DetectionValidator() : this(LaandmrkDetectorPINVOKE.new_DetectionValidator__SWIG_0(), true) {
  }

  public DetectionValidator(DetectionValidator other) : this(LaandmrkDetectorPINVOKE.new_DetectionValidator__SWIG_1(DetectionValidator.getCPtr(other)), true) {
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

  public double Check(SWIGTYPE_p_cv__Vec3d orientation, SWIGTYPE_p_cv__Mat_T_uchar_t intensity_img, SWIGTYPE_p_cv__Mat_T_double_t detected_landmarks) {
    double ret = LaandmrkDetectorPINVOKE.DetectionValidator_Check(swigCPtr, SWIGTYPE_p_cv__Vec3d.getCPtr(orientation), SWIGTYPE_p_cv__Mat_T_uchar_t.getCPtr(intensity_img), SWIGTYPE_p_cv__Mat_T_double_t.getCPtr(detected_landmarks));
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Read(string location) {
    LaandmrkDetectorPINVOKE.DetectionValidator_Read(swigCPtr, location);
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

  public int GetViewId(SWIGTYPE_p_cv__Vec3d orientation) {
    int ret = LaandmrkDetectorPINVOKE.DetectionValidator_GetViewId(swigCPtr, SWIGTYPE_p_cv__Vec3d.getCPtr(orientation));
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
