//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Int_List2N : global::System.IDisposable, global::System.Collections.IEnumerable
    , global::System.Collections.Generic.IEnumerable<Int_List>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Int_List2N(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Int_List2N obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Int_List2N() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LaandmrkDetectorPINVOKE.delete_Int_List2N(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public Int_List2N(global::System.Collections.ICollection c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Int_List element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public Int_List this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(Int_List[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(Int_List[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, Int_List[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  global::System.Collections.Generic.IEnumerator<Int_List> global::System.Collections.Generic.IEnumerable<Int_List>.GetEnumerator() {
    return new Int_List2NEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new Int_List2NEnumerator(this);
  }

  public Int_List2NEnumerator GetEnumerator() {
    return new Int_List2NEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class Int_List2NEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<Int_List>
  {
    private Int_List2N collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public Int_List2NEnumerator(Int_List2N collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public Int_List Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (Int_List)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    LaandmrkDetectorPINVOKE.Int_List2N_Clear(swigCPtr);
  }

  public void Add(Int_List x) {
    LaandmrkDetectorPINVOKE.Int_List2N_Add(swigCPtr, Int_List.getCPtr(x));
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = LaandmrkDetectorPINVOKE.Int_List2N_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = LaandmrkDetectorPINVOKE.Int_List2N_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    LaandmrkDetectorPINVOKE.Int_List2N_reserve(swigCPtr, n);
  }

  public Int_List2N() : this(LaandmrkDetectorPINVOKE.new_Int_List2N__SWIG_0(), true) {
  }

  public Int_List2N(Int_List2N other) : this(LaandmrkDetectorPINVOKE.new_Int_List2N__SWIG_1(Int_List2N.getCPtr(other)), true) {
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

  public Int_List2N(int capacity) : this(LaandmrkDetectorPINVOKE.new_Int_List2N__SWIG_2(capacity), true) {
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

  private Int_List getitemcopy(int index) {
    Int_List ret = new Int_List(LaandmrkDetectorPINVOKE.Int_List2N_getitemcopy(swigCPtr, index), true);
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private Int_List getitem(int index) {
    Int_List ret = new Int_List(LaandmrkDetectorPINVOKE.Int_List2N_getitem(swigCPtr, index), false);
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, Int_List val) {
    LaandmrkDetectorPINVOKE.Int_List2N_setitem(swigCPtr, index, Int_List.getCPtr(val));
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(Int_List2N values) {
    LaandmrkDetectorPINVOKE.Int_List2N_AddRange(swigCPtr, Int_List2N.getCPtr(values));
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

  public Int_List2N GetRange(int index, int count) {
    global::System.IntPtr cPtr = LaandmrkDetectorPINVOKE.Int_List2N_GetRange(swigCPtr, index, count);
    Int_List2N ret = (cPtr == global::System.IntPtr.Zero) ? null : new Int_List2N(cPtr, true);
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, Int_List x) {
    LaandmrkDetectorPINVOKE.Int_List2N_Insert(swigCPtr, index, Int_List.getCPtr(x));
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, Int_List2N values) {
    LaandmrkDetectorPINVOKE.Int_List2N_InsertRange(swigCPtr, index, Int_List2N.getCPtr(values));
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    LaandmrkDetectorPINVOKE.Int_List2N_RemoveAt(swigCPtr, index);
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    LaandmrkDetectorPINVOKE.Int_List2N_RemoveRange(swigCPtr, index, count);
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

  public static Int_List2N Repeat(Int_List value, int count) {
    global::System.IntPtr cPtr = LaandmrkDetectorPINVOKE.Int_List2N_Repeat(Int_List.getCPtr(value), count);
    Int_List2N ret = (cPtr == global::System.IntPtr.Zero) ? null : new Int_List2N(cPtr, true);
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    LaandmrkDetectorPINVOKE.Int_List2N_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    LaandmrkDetectorPINVOKE.Int_List2N_Reverse__SWIG_1(swigCPtr, index, count);
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, Int_List2N values) {
    LaandmrkDetectorPINVOKE.Int_List2N_SetRange(swigCPtr, index, Int_List2N.getCPtr(values));
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

}
