//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SharpFace
{

    public class SWIGTYPE_p_cv__Matx22f
    {

        private volatile System.IntPtr swigCPtr;

        public SWIGTYPE_p_cv__Matx22f(System.IntPtr ptr)
        {
            swigCPtr = ptr;
        }

        public SWIGTYPE_p_cv__Matx22f()
        {
            swigCPtr = System.IntPtr.Zero;
        }

        public System.IntPtr Pointer
        {
            get
            {
                return swigCPtr;
            }
        }
    }

}
