//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace LandmarkDetector
{

    public class SWIGTYPE_p_cv__Rect_T_double_t
    {

        private volatile System.IntPtr swigCPtr;

        protected SWIGTYPE_p_cv__Rect_T_double_t()
        {
            swigCPtr = System.IntPtr.Zero;
        }

        internal System.IntPtr Pointer
        {
            get
            {
                return swigCPtr;
            }
        }
    }

}
