//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CVPoint2D_Pair : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CVPoint2D_Pair(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CVPoint2D_Pair obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CVPoint2D_Pair() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LaandmrkDetectorPINVOKE.delete_CVPoint2D_Pair(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public CVPoint2D_Pair() : this(LaandmrkDetectorPINVOKE.new_CVPoint2D_Pair__SWIG_0(), true) {
  }

  public CVPoint2D_Pair(SWIGTYPE_p_cv__Point2d t, SWIGTYPE_p_cv__Point2d u) : this(LaandmrkDetectorPINVOKE.new_CVPoint2D_Pair__SWIG_1(SWIGTYPE_p_cv__Point2d.getCPtr(t), SWIGTYPE_p_cv__Point2d.getCPtr(u)), true) {
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

  public CVPoint2D_Pair(CVPoint2D_Pair p) : this(LaandmrkDetectorPINVOKE.new_CVPoint2D_Pair__SWIG_2(CVPoint2D_Pair.getCPtr(p)), true) {
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_cv__Point2d first {
    set {
      LaandmrkDetectorPINVOKE.CVPoint2D_Pair_first_set(swigCPtr, SWIGTYPE_p_cv__Point2d.getCPtr(value));
      if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_cv__Point2d ret = new SWIGTYPE_p_cv__Point2d(LaandmrkDetectorPINVOKE.CVPoint2D_Pair_first_get(swigCPtr), true);
      if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_cv__Point2d second {
    set {
      LaandmrkDetectorPINVOKE.CVPoint2D_Pair_second_set(swigCPtr, SWIGTYPE_p_cv__Point2d.getCPtr(value));
      if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_cv__Point2d ret = new SWIGTYPE_p_cv__Point2d(LaandmrkDetectorPINVOKE.CVPoint2D_Pair_second_get(swigCPtr), true);
      if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

}
