//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class DetectionValidator : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DetectionValidator(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DetectionValidator obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~DetectionValidator() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LandmarkDetectorPINVOKE.delete_DetectionValidator(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public int validator_type {
    set {
      LandmarkDetectorPINVOKE.DetectionValidator_validator_type_set(swigCPtr, value);
    } 
    get {
      int ret = LandmarkDetectorPINVOKE.DetectionValidator_validator_type_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_vectorT_cv__Vec3d_t orientations {
    set {
      LandmarkDetectorPINVOKE.DetectionValidator_orientations_set(swigCPtr, SWIGTYPE_p_vectorT_cv__Vec3d_t.getCPtr(value));
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_vectorT_cv__Vec3d_t ret = new SWIGTYPE_p_vectorT_cv__Vec3d_t(LandmarkDetectorPINVOKE.DetectionValidator_orientations_get(swigCPtr), true);
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_vectorT_PAW_t paws {
    set {
      LandmarkDetectorPINVOKE.DetectionValidator_paws_set(swigCPtr, SWIGTYPE_p_vectorT_PAW_t.getCPtr(value));
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_vectorT_PAW_t ret = new SWIGTYPE_p_vectorT_PAW_t(LandmarkDetectorPINVOKE.DetectionValidator_paws_get(swigCPtr), true);
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_vectorT_double_t bs {
    set {
      LandmarkDetectorPINVOKE.DetectionValidator_bs_set(swigCPtr, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_vectorT_double_t ret = new SWIGTYPE_p_vectorT_double_t(LandmarkDetectorPINVOKE.DetectionValidator_bs_get(swigCPtr), true);
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_vectorT_cv__Mat_T_double_t_t ws {
    set {
      LandmarkDetectorPINVOKE.DetectionValidator_ws_set(swigCPtr, SWIGTYPE_p_vectorT_cv__Mat_T_double_t_t.getCPtr(value));
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_vectorT_cv__Mat_T_double_t_t ret = new SWIGTYPE_p_vectorT_cv__Mat_T_double_t_t(LandmarkDetectorPINVOKE.DetectionValidator_ws_get(swigCPtr), true);
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_vectorT_vectorT_cv__Mat_T_double_t_t_t ws_nn {
    set {
      LandmarkDetectorPINVOKE.DetectionValidator_ws_nn_set(swigCPtr, SWIGTYPE_p_vectorT_vectorT_cv__Mat_T_double_t_t_t.getCPtr(value));
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_vectorT_vectorT_cv__Mat_T_double_t_t_t ret = new SWIGTYPE_p_vectorT_vectorT_cv__Mat_T_double_t_t_t(LandmarkDetectorPINVOKE.DetectionValidator_ws_nn_get(swigCPtr), true);
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_vectorT_int_t activation_fun {
    set {
      LandmarkDetectorPINVOKE.DetectionValidator_activation_fun_set(swigCPtr, SWIGTYPE_p_vectorT_int_t.getCPtr(value));
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_vectorT_int_t ret = new SWIGTYPE_p_vectorT_int_t(LandmarkDetectorPINVOKE.DetectionValidator_activation_fun_get(swigCPtr), true);
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_vectorT_int_t output_fun {
    set {
      LandmarkDetectorPINVOKE.DetectionValidator_output_fun_set(swigCPtr, SWIGTYPE_p_vectorT_int_t.getCPtr(value));
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_vectorT_int_t ret = new SWIGTYPE_p_vectorT_int_t(LandmarkDetectorPINVOKE.DetectionValidator_output_fun_get(swigCPtr), true);
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_vectorT_vectorT_vectorT_vectorT_cv__Mat_T_float_t_t_t_t_t cnn_convolutional_layers {
    set {
      LandmarkDetectorPINVOKE.DetectionValidator_cnn_convolutional_layers_set(swigCPtr, SWIGTYPE_p_vectorT_vectorT_vectorT_vectorT_cv__Mat_T_float_t_t_t_t_t.getCPtr(value));
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_vectorT_vectorT_vectorT_vectorT_cv__Mat_T_float_t_t_t_t_t ret = new SWIGTYPE_p_vectorT_vectorT_vectorT_vectorT_cv__Mat_T_float_t_t_t_t_t(LandmarkDetectorPINVOKE.DetectionValidator_cnn_convolutional_layers_get(swigCPtr), true);
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_vectorT_vectorT_vectorT_vectorT_pairT_int_cv__Mat_T_double_t_t_t_t_t_t cnn_convolutional_layers_dft {
    set {
      LandmarkDetectorPINVOKE.DetectionValidator_cnn_convolutional_layers_dft_set(swigCPtr, SWIGTYPE_p_vectorT_vectorT_vectorT_vectorT_pairT_int_cv__Mat_T_double_t_t_t_t_t_t.getCPtr(value));
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_vectorT_vectorT_vectorT_vectorT_pairT_int_cv__Mat_T_double_t_t_t_t_t_t ret = new SWIGTYPE_p_vectorT_vectorT_vectorT_vectorT_pairT_int_cv__Mat_T_double_t_t_t_t_t_t(LandmarkDetectorPINVOKE.DetectionValidator_cnn_convolutional_layers_dft_get(swigCPtr), true);
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_vectorT_vectorT_vectorT_float_t_t_t cnn_convolutional_layers_bias {
    set {
      LandmarkDetectorPINVOKE.DetectionValidator_cnn_convolutional_layers_bias_set(swigCPtr, SWIGTYPE_p_vectorT_vectorT_vectorT_float_t_t_t.getCPtr(value));
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_vectorT_vectorT_vectorT_float_t_t_t ret = new SWIGTYPE_p_vectorT_vectorT_vectorT_float_t_t_t(LandmarkDetectorPINVOKE.DetectionValidator_cnn_convolutional_layers_bias_get(swigCPtr), true);
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_vectorT_vectorT_int_t_t cnn_subsampling_layers {
    set {
      LandmarkDetectorPINVOKE.DetectionValidator_cnn_subsampling_layers_set(swigCPtr, SWIGTYPE_p_vectorT_vectorT_int_t_t.getCPtr(value));
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_vectorT_vectorT_int_t_t ret = new SWIGTYPE_p_vectorT_vectorT_int_t_t(LandmarkDetectorPINVOKE.DetectionValidator_cnn_subsampling_layers_get(swigCPtr), true);
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_vectorT_vectorT_cv__Mat_T_float_t_t_t cnn_fully_connected_layers_weights {
    set {
      LandmarkDetectorPINVOKE.DetectionValidator_cnn_fully_connected_layers_weights_set(swigCPtr, SWIGTYPE_p_vectorT_vectorT_cv__Mat_T_float_t_t_t.getCPtr(value));
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_vectorT_vectorT_cv__Mat_T_float_t_t_t ret = new SWIGTYPE_p_vectorT_vectorT_cv__Mat_T_float_t_t_t(LandmarkDetectorPINVOKE.DetectionValidator_cnn_fully_connected_layers_weights_get(swigCPtr), true);
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_vectorT_vectorT_float_t_t cnn_fully_connected_layers_bias {
    set {
      LandmarkDetectorPINVOKE.DetectionValidator_cnn_fully_connected_layers_bias_set(swigCPtr, SWIGTYPE_p_vectorT_vectorT_float_t_t.getCPtr(value));
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_vectorT_vectorT_float_t_t ret = new SWIGTYPE_p_vectorT_vectorT_float_t_t(LandmarkDetectorPINVOKE.DetectionValidator_cnn_fully_connected_layers_bias_get(swigCPtr), true);
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_vectorT_vectorT_int_t_t cnn_layer_types {
    set {
      LandmarkDetectorPINVOKE.DetectionValidator_cnn_layer_types_set(swigCPtr, SWIGTYPE_p_vectorT_vectorT_int_t_t.getCPtr(value));
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_vectorT_vectorT_int_t_t ret = new SWIGTYPE_p_vectorT_vectorT_int_t_t(LandmarkDetectorPINVOKE.DetectionValidator_cnn_layer_types_get(swigCPtr), true);
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_vectorT_vectorT_cv__Mat_T_float_t_t_t cnn_fully_connected_layers_biases {
    set {
      LandmarkDetectorPINVOKE.DetectionValidator_cnn_fully_connected_layers_biases_set(swigCPtr, SWIGTYPE_p_vectorT_vectorT_cv__Mat_T_float_t_t_t.getCPtr(value));
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_vectorT_vectorT_cv__Mat_T_float_t_t_t ret = new SWIGTYPE_p_vectorT_vectorT_cv__Mat_T_float_t_t_t(LandmarkDetectorPINVOKE.DetectionValidator_cnn_fully_connected_layers_biases_get(swigCPtr), true);
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_vectorT_cv__Mat_T_double_t_t mean_images {
    set {
      LandmarkDetectorPINVOKE.DetectionValidator_mean_images_set(swigCPtr, SWIGTYPE_p_vectorT_cv__Mat_T_double_t_t.getCPtr(value));
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_vectorT_cv__Mat_T_double_t_t ret = new SWIGTYPE_p_vectorT_cv__Mat_T_double_t_t(LandmarkDetectorPINVOKE.DetectionValidator_mean_images_get(swigCPtr), true);
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_vectorT_cv__Mat_T_double_t_t standard_deviations {
    set {
      LandmarkDetectorPINVOKE.DetectionValidator_standard_deviations_set(swigCPtr, SWIGTYPE_p_vectorT_cv__Mat_T_double_t_t.getCPtr(value));
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_vectorT_cv__Mat_T_double_t_t ret = new SWIGTYPE_p_vectorT_cv__Mat_T_double_t_t(LandmarkDetectorPINVOKE.DetectionValidator_standard_deviations_get(swigCPtr), true);
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public DetectionValidator() : this(LandmarkDetectorPINVOKE.new_DetectionValidator__SWIG_0(), true) {
  }

  public DetectionValidator(DetectionValidator other) : this(LandmarkDetectorPINVOKE.new_DetectionValidator__SWIG_1(DetectionValidator.getCPtr(other)), true) {
    if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

  public double Check(SWIGTYPE_p_cv__Vec3d orientation, SWIGTYPE_p_cv__Mat_T_uchar_t intensity_img, SWIGTYPE_p_cv__Mat_T_double_t detected_landmarks) {
    double ret = LandmarkDetectorPINVOKE.DetectionValidator_Check(swigCPtr, SWIGTYPE_p_cv__Vec3d.getCPtr(orientation), SWIGTYPE_p_cv__Mat_T_uchar_t.getCPtr(intensity_img), SWIGTYPE_p_cv__Mat_T_double_t.getCPtr(detected_landmarks));
    if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Read(SWIGTYPE_p_string location) {
    LandmarkDetectorPINVOKE.DetectionValidator_Read(swigCPtr, SWIGTYPE_p_string.getCPtr(location));
    if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

  public int GetViewId(SWIGTYPE_p_cv__Vec3d orientation) {
    int ret = LandmarkDetectorPINVOKE.DetectionValidator_GetViewId(swigCPtr, SWIGTYPE_p_cv__Vec3d.getCPtr(orientation));
    if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
