//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class LaandmrkDetector {
  public static bool DetectLandmarksInVideo(SWIGTYPE_p_cv__Mat_T_uchar_t grayscale_image, SWIGTYPE_p_CLNF clnf_model, SWIGTYPE_p_FaceModelParameters arg2) {
    bool ret = LaandmrkDetectorPINVOKE.DetectLandmarksInVideo__SWIG_0(SWIGTYPE_p_cv__Mat_T_uchar_t.getCPtr(grayscale_image), SWIGTYPE_p_CLNF.getCPtr(clnf_model), SWIGTYPE_p_FaceModelParameters.getCPtr(arg2));
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool DetectLandmarksInVideo(SWIGTYPE_p_cv__Mat_T_uchar_t grayscale_image, SWIGTYPE_p_cv__Rect_T_double_t bounding_box, SWIGTYPE_p_CLNF clnf_model, SWIGTYPE_p_FaceModelParameters arg3) {
    bool ret = LaandmrkDetectorPINVOKE.DetectLandmarksInVideo__SWIG_1(SWIGTYPE_p_cv__Mat_T_uchar_t.getCPtr(grayscale_image), SWIGTYPE_p_cv__Rect_T_double_t.getCPtr(bounding_box), SWIGTYPE_p_CLNF.getCPtr(clnf_model), SWIGTYPE_p_FaceModelParameters.getCPtr(arg3));
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool DetectLandmarksInImage(SWIGTYPE_p_cv__Mat_T_uchar_t grayscale_image, SWIGTYPE_p_CLNF clnf_model, SWIGTYPE_p_FaceModelParameters arg2) {
    bool ret = LaandmrkDetectorPINVOKE.DetectLandmarksInImage__SWIG_0(SWIGTYPE_p_cv__Mat_T_uchar_t.getCPtr(grayscale_image), SWIGTYPE_p_CLNF.getCPtr(clnf_model), SWIGTYPE_p_FaceModelParameters.getCPtr(arg2));
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool DetectLandmarksInImage(SWIGTYPE_p_cv__Mat_T_uchar_t grayscale_image, SWIGTYPE_p_cv__Rect_T_double_t bounding_box, SWIGTYPE_p_CLNF clnf_model, SWIGTYPE_p_FaceModelParameters arg3) {
    bool ret = LaandmrkDetectorPINVOKE.DetectLandmarksInImage__SWIG_1(SWIGTYPE_p_cv__Mat_T_uchar_t.getCPtr(grayscale_image), SWIGTYPE_p_cv__Rect_T_double_t.getCPtr(bounding_box), SWIGTYPE_p_CLNF.getCPtr(clnf_model), SWIGTYPE_p_FaceModelParameters.getCPtr(arg3));
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_cv__Vec6d GetPoseCamera(SWIGTYPE_p_CLNF clnf_model, double fx, double fy, double cx, double cy) {
    SWIGTYPE_p_cv__Vec6d ret = new SWIGTYPE_p_cv__Vec6d(LaandmrkDetectorPINVOKE.GetPoseCamera(SWIGTYPE_p_CLNF.getCPtr(clnf_model), fx, fy, cx, cy), true);
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_cv__Vec6d GetPoseWorld(SWIGTYPE_p_CLNF clnf_model, double fx, double fy, double cx, double cy) {
    SWIGTYPE_p_cv__Vec6d ret = new SWIGTYPE_p_cv__Vec6d(LaandmrkDetectorPINVOKE.GetPoseWorld(SWIGTYPE_p_CLNF.getCPtr(clnf_model), fx, fy, cx, cy), true);
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_cv__Vec6d GetCorrectedPoseCamera(SWIGTYPE_p_CLNF clnf_model, double fx, double fy, double cx, double cy) {
    SWIGTYPE_p_cv__Vec6d ret = new SWIGTYPE_p_cv__Vec6d(LaandmrkDetectorPINVOKE.GetCorrectedPoseCamera(SWIGTYPE_p_CLNF.getCPtr(clnf_model), fx, fy, cx, cy), true);
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_cv__Vec6d GetCorrectedPoseWorld(SWIGTYPE_p_CLNF clnf_model, double fx, double fy, double cx, double cy) {
    SWIGTYPE_p_cv__Vec6d ret = new SWIGTYPE_p_cv__Vec6d(LaandmrkDetectorPINVOKE.GetCorrectedPoseWorld(SWIGTYPE_p_CLNF.getCPtr(clnf_model), fx, fy, cx, cy), true);
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void get_video_input_output_params(String_List input_video_file, String_List output_files, String_List output_video_files, SWIGTYPE_p_bool world_coordinates_pose, SWIGTYPE_p_std__string output_codec, String_List arguments) {
    LaandmrkDetectorPINVOKE.get_video_input_output_params(String_List.getCPtr(input_video_file), String_List.getCPtr(output_files), String_List.getCPtr(output_video_files), SWIGTYPE_p_bool.getCPtr(world_coordinates_pose), SWIGTYPE_p_std__string.getCPtr(output_codec), String_List.getCPtr(arguments));
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void get_camera_params(SWIGTYPE_p_int device, SWIGTYPE_p_float fx, SWIGTYPE_p_float fy, SWIGTYPE_p_float cx, SWIGTYPE_p_float cy, String_List arguments) {
    LaandmrkDetectorPINVOKE.get_camera_params(SWIGTYPE_p_int.getCPtr(device), SWIGTYPE_p_float.getCPtr(fx), SWIGTYPE_p_float.getCPtr(fy), SWIGTYPE_p_float.getCPtr(cx), SWIGTYPE_p_float.getCPtr(cy), String_List.getCPtr(arguments));
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void get_image_input_output_params(String_List input_image_files, String_List output_feature_files, String_List output_pose_files, String_List output_image_files, CVDoubleRect_List input_bounding_boxes, String_List arguments) {
    LaandmrkDetectorPINVOKE.get_image_input_output_params(String_List.getCPtr(input_image_files), String_List.getCPtr(output_feature_files), String_List.getCPtr(output_pose_files), String_List.getCPtr(output_image_files), CVDoubleRect_List.getCPtr(input_bounding_boxes), String_List.getCPtr(arguments));
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void matchTemplate_m(SWIGTYPE_p_cv__Mat_T_float_t input_img, SWIGTYPE_p_cv__Mat_T_double_t img_dft, SWIGTYPE_p_cv__Mat _integral_img, SWIGTYPE_p_cv__Mat _integral_img_sq, SWIGTYPE_p_cv__Mat_T_float_t templ, Int_DoubleMat_Map templ_dfts, SWIGTYPE_p_cv__Mat_T_float_t result, int method) {
    LaandmrkDetectorPINVOKE.matchTemplate_m(SWIGTYPE_p_cv__Mat_T_float_t.getCPtr(input_img), SWIGTYPE_p_cv__Mat_T_double_t.getCPtr(img_dft), SWIGTYPE_p_cv__Mat.getCPtr(_integral_img), SWIGTYPE_p_cv__Mat.getCPtr(_integral_img_sq), SWIGTYPE_p_cv__Mat_T_float_t.getCPtr(templ), Int_DoubleMat_Map.getCPtr(templ_dfts), SWIGTYPE_p_cv__Mat_T_float_t.getCPtr(result), method);
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

  public static SWIGTYPE_p_cv__Matx22d AlignShapesKabsch2D(SWIGTYPE_p_cv__Mat_T_double_t align_from, SWIGTYPE_p_cv__Mat_T_double_t align_to) {
    SWIGTYPE_p_cv__Matx22d ret = new SWIGTYPE_p_cv__Matx22d(LaandmrkDetectorPINVOKE.AlignShapesKabsch2D(SWIGTYPE_p_cv__Mat_T_double_t.getCPtr(align_from), SWIGTYPE_p_cv__Mat_T_double_t.getCPtr(align_to)), true);
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_cv__Matx22d AlignShapesWithScale(SWIGTYPE_p_cv__Mat_T_double_t src, SWIGTYPE_p_cv__Mat_T_double_t dst) {
    SWIGTYPE_p_cv__Matx22d ret = new SWIGTYPE_p_cv__Matx22d(LaandmrkDetectorPINVOKE.AlignShapesWithScale(SWIGTYPE_p_cv__Mat_T_double_t.getCPtr(src), SWIGTYPE_p_cv__Mat_T_double_t.getCPtr(dst)), true);
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void Project(SWIGTYPE_p_cv__Mat_T_double_t dest, SWIGTYPE_p_cv__Mat_T_double_t mesh, double fx, double fy, double cx, double cy) {
    LaandmrkDetectorPINVOKE.Project(SWIGTYPE_p_cv__Mat_T_double_t.getCPtr(dest), SWIGTYPE_p_cv__Mat_T_double_t.getCPtr(mesh), fx, fy, cx, cy);
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void DrawBox(SWIGTYPE_p_cv__Mat image, SWIGTYPE_p_cv__Vec6d pose, SWIGTYPE_p_cv__Scalar color, int thickness, float fx, float fy, float cx, float cy) {
    LaandmrkDetectorPINVOKE.DrawBox__SWIG_0(SWIGTYPE_p_cv__Mat.getCPtr(image), SWIGTYPE_p_cv__Vec6d.getCPtr(pose), SWIGTYPE_p_cv__Scalar.getCPtr(color), thickness, fx, fy, cx, cy);
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

  public static CVPoint2D_Pair_List CalculateBox(SWIGTYPE_p_cv__Vec6d pose, float fx, float fy, float cx, float cy) {
    CVPoint2D_Pair_List ret = new CVPoint2D_Pair_List(LaandmrkDetectorPINVOKE.CalculateBox(SWIGTYPE_p_cv__Vec6d.getCPtr(pose), fx, fy, cx, cy), true);
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void DrawBox(CVPoint_Pair_List lines, SWIGTYPE_p_cv__Mat image, SWIGTYPE_p_cv__Scalar color, int thickness) {
    LaandmrkDetectorPINVOKE.DrawBox__SWIG_1(CVPoint_Pair_List.getCPtr(lines), SWIGTYPE_p_cv__Mat.getCPtr(image), SWIGTYPE_p_cv__Scalar.getCPtr(color), thickness);
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

  public static CVPoint2D_List CalculateLandmarks(SWIGTYPE_p_cv__Mat_T_double_t shape2D, SWIGTYPE_p_cv__Mat_T_int_t visibilities) {
    CVPoint2D_List ret = new CVPoint2D_List(LaandmrkDetectorPINVOKE.CalculateLandmarks__SWIG_0(SWIGTYPE_p_cv__Mat_T_double_t.getCPtr(shape2D), SWIGTYPE_p_cv__Mat_T_int_t.getCPtr(visibilities)), true);
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static CVPoint2D_List CalculateLandmarks(CLNF clnf_model) {
    CVPoint2D_List ret = new CVPoint2D_List(LaandmrkDetectorPINVOKE.CalculateLandmarks__SWIG_1(CLNF.getCPtr(clnf_model)), true);
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void DrawLandmarks(SWIGTYPE_p_cv__Mat img, CVPoint_List landmarks) {
    LaandmrkDetectorPINVOKE.DrawLandmarks(SWIGTYPE_p_cv__Mat.getCPtr(img), CVPoint_List.getCPtr(landmarks));
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void Draw(SWIGTYPE_p_cv__Mat img, SWIGTYPE_p_cv__Mat_T_double_t shape2D, SWIGTYPE_p_cv__Mat_T_int_t visibilities) {
    LaandmrkDetectorPINVOKE.Draw__SWIG_0(SWIGTYPE_p_cv__Mat.getCPtr(img), SWIGTYPE_p_cv__Mat_T_double_t.getCPtr(shape2D), SWIGTYPE_p_cv__Mat_T_int_t.getCPtr(visibilities));
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void Draw(SWIGTYPE_p_cv__Mat img, SWIGTYPE_p_cv__Mat_T_double_t shape2D) {
    LaandmrkDetectorPINVOKE.Draw__SWIG_1(SWIGTYPE_p_cv__Mat.getCPtr(img), SWIGTYPE_p_cv__Mat_T_double_t.getCPtr(shape2D));
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void Draw(SWIGTYPE_p_cv__Mat img, CLNF clnf_model) {
    LaandmrkDetectorPINVOKE.Draw__SWIG_2(SWIGTYPE_p_cv__Mat.getCPtr(img), CLNF.getCPtr(clnf_model));
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

  public static SWIGTYPE_p_cv__Matx33d Euler2RotationMatrix(SWIGTYPE_p_cv__Vec3d eulerAngles) {
    SWIGTYPE_p_cv__Matx33d ret = new SWIGTYPE_p_cv__Matx33d(LaandmrkDetectorPINVOKE.Euler2RotationMatrix(SWIGTYPE_p_cv__Vec3d.getCPtr(eulerAngles)), true);
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_cv__Vec3d RotationMatrix2Euler(SWIGTYPE_p_cv__Matx33d rotation_matrix) {
    SWIGTYPE_p_cv__Vec3d ret = new SWIGTYPE_p_cv__Vec3d(LaandmrkDetectorPINVOKE.RotationMatrix2Euler(SWIGTYPE_p_cv__Matx33d.getCPtr(rotation_matrix)), true);
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_cv__Vec3d Euler2AxisAngle(SWIGTYPE_p_cv__Vec3d euler) {
    SWIGTYPE_p_cv__Vec3d ret = new SWIGTYPE_p_cv__Vec3d(LaandmrkDetectorPINVOKE.Euler2AxisAngle(SWIGTYPE_p_cv__Vec3d.getCPtr(euler)), true);
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_cv__Vec3d AxisAngle2Euler(SWIGTYPE_p_cv__Vec3d axis_angle) {
    SWIGTYPE_p_cv__Vec3d ret = new SWIGTYPE_p_cv__Vec3d(LaandmrkDetectorPINVOKE.AxisAngle2Euler(SWIGTYPE_p_cv__Vec3d.getCPtr(axis_angle)), true);
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_cv__Matx33d AxisAngle2RotationMatrix(SWIGTYPE_p_cv__Vec3d axis_angle) {
    SWIGTYPE_p_cv__Matx33d ret = new SWIGTYPE_p_cv__Matx33d(LaandmrkDetectorPINVOKE.AxisAngle2RotationMatrix(SWIGTYPE_p_cv__Vec3d.getCPtr(axis_angle)), true);
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_cv__Vec3d RotationMatrix2AxisAngle(SWIGTYPE_p_cv__Matx33d rotation_matrix) {
    SWIGTYPE_p_cv__Vec3d ret = new SWIGTYPE_p_cv__Vec3d(LaandmrkDetectorPINVOKE.RotationMatrix2AxisAngle(SWIGTYPE_p_cv__Matx33d.getCPtr(rotation_matrix)), true);
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool DetectFaces(CVDoubleRect_List o_regions, SWIGTYPE_p_cv__Mat_T_uchar_t intensity) {
    bool ret = LaandmrkDetectorPINVOKE.DetectFaces__SWIG_0(CVDoubleRect_List.getCPtr(o_regions), SWIGTYPE_p_cv__Mat_T_uchar_t.getCPtr(intensity));
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool DetectFaces(CVDoubleRect_List o_regions, SWIGTYPE_p_cv__Mat_T_uchar_t intensity, SWIGTYPE_p_cv__CascadeClassifier classifier) {
    bool ret = LaandmrkDetectorPINVOKE.DetectFaces__SWIG_1(CVDoubleRect_List.getCPtr(o_regions), SWIGTYPE_p_cv__Mat_T_uchar_t.getCPtr(intensity), SWIGTYPE_p_cv__CascadeClassifier.getCPtr(classifier));
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool DetectSingleFace(SWIGTYPE_p_cv__Rect_T_double_t o_region, SWIGTYPE_p_cv__Mat_T_uchar_t intensity, SWIGTYPE_p_cv__CascadeClassifier classifier, SWIGTYPE_p_cv__Point preference) {
    bool ret = LaandmrkDetectorPINVOKE.DetectSingleFace__SWIG_0(SWIGTYPE_p_cv__Rect_T_double_t.getCPtr(o_region), SWIGTYPE_p_cv__Mat_T_uchar_t.getCPtr(intensity), SWIGTYPE_p_cv__CascadeClassifier.getCPtr(classifier), SWIGTYPE_p_cv__Point.getCPtr(preference));
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool DetectSingleFace(SWIGTYPE_p_cv__Rect_T_double_t o_region, SWIGTYPE_p_cv__Mat_T_uchar_t intensity, SWIGTYPE_p_cv__CascadeClassifier classifier) {
    bool ret = LaandmrkDetectorPINVOKE.DetectSingleFace__SWIG_1(SWIGTYPE_p_cv__Rect_T_double_t.getCPtr(o_region), SWIGTYPE_p_cv__Mat_T_uchar_t.getCPtr(intensity), SWIGTYPE_p_cv__CascadeClassifier.getCPtr(classifier));
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool DetectFacesHOG(CVDoubleRect_List o_regions, SWIGTYPE_p_cv__Mat_T_uchar_t intensity, Double_List confidences) {
    bool ret = LaandmrkDetectorPINVOKE.DetectFacesHOG__SWIG_0(CVDoubleRect_List.getCPtr(o_regions), SWIGTYPE_p_cv__Mat_T_uchar_t.getCPtr(intensity), Double_List.getCPtr(confidences));
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool DetectFacesHOG(CVDoubleRect_List o_regions, SWIGTYPE_p_cv__Mat_T_uchar_t intensity, SWIGTYPE_p_dlib__frontal_face_detector classifier, Double_List confidences) {
    bool ret = LaandmrkDetectorPINVOKE.DetectFacesHOG__SWIG_1(CVDoubleRect_List.getCPtr(o_regions), SWIGTYPE_p_cv__Mat_T_uchar_t.getCPtr(intensity), SWIGTYPE_p_dlib__frontal_face_detector.getCPtr(classifier), Double_List.getCPtr(confidences));
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool DetectSingleFaceHOG(SWIGTYPE_p_cv__Rect_T_double_t o_region, SWIGTYPE_p_cv__Mat_T_uchar_t intensity, SWIGTYPE_p_dlib__frontal_face_detector classifier, SWIGTYPE_p_double confidence, SWIGTYPE_p_cv__Point preference) {
    bool ret = LaandmrkDetectorPINVOKE.DetectSingleFaceHOG__SWIG_0(SWIGTYPE_p_cv__Rect_T_double_t.getCPtr(o_region), SWIGTYPE_p_cv__Mat_T_uchar_t.getCPtr(intensity), SWIGTYPE_p_dlib__frontal_face_detector.getCPtr(classifier), SWIGTYPE_p_double.getCPtr(confidence), SWIGTYPE_p_cv__Point.getCPtr(preference));
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool DetectSingleFaceHOG(SWIGTYPE_p_cv__Rect_T_double_t o_region, SWIGTYPE_p_cv__Mat_T_uchar_t intensity, SWIGTYPE_p_dlib__frontal_face_detector classifier, SWIGTYPE_p_double confidence) {
    bool ret = LaandmrkDetectorPINVOKE.DetectSingleFaceHOG__SWIG_1(SWIGTYPE_p_cv__Rect_T_double_t.getCPtr(o_region), SWIGTYPE_p_cv__Mat_T_uchar_t.getCPtr(intensity), SWIGTYPE_p_dlib__frontal_face_detector.getCPtr(classifier), SWIGTYPE_p_double.getCPtr(confidence));
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void ReadMatBin(SWIGTYPE_p_std__ifstream stream, SWIGTYPE_p_cv__Mat output_mat) {
    LaandmrkDetectorPINVOKE.ReadMatBin(SWIGTYPE_p_std__ifstream.getCPtr(stream), SWIGTYPE_p_cv__Mat.getCPtr(output_mat));
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void ReadMat(SWIGTYPE_p_std__ifstream stream, SWIGTYPE_p_cv__Mat output_matrix) {
    LaandmrkDetectorPINVOKE.ReadMat(SWIGTYPE_p_std__ifstream.getCPtr(stream), SWIGTYPE_p_cv__Mat.getCPtr(output_matrix));
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void SkipComments(SWIGTYPE_p_std__ifstream stream) {
    LaandmrkDetectorPINVOKE.SkipComments(SWIGTYPE_p_std__ifstream.getCPtr(stream));
    if (LaandmrkDetectorPINVOKE.SWIGPendingException.Pending) throw LaandmrkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

}
