//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class SVR_patch_expert : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SVR_patch_expert(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SVR_patch_expert obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~SVR_patch_expert() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LandmarkDetectorPINVOKE.delete_SVR_patch_expert(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public int type {
    set {
      LandmarkDetectorPINVOKE.SVR_patch_expert_type_set(swigCPtr, value);
    } 
    get {
      int ret = LandmarkDetectorPINVOKE.SVR_patch_expert_type_get(swigCPtr);
      return ret;
    } 
  }

  public double scaling {
    set {
      LandmarkDetectorPINVOKE.SVR_patch_expert_scaling_set(swigCPtr, value);
    } 
    get {
      double ret = LandmarkDetectorPINVOKE.SVR_patch_expert_scaling_get(swigCPtr);
      return ret;
    } 
  }

  public double bias {
    set {
      LandmarkDetectorPINVOKE.SVR_patch_expert_bias_set(swigCPtr, value);
    } 
    get {
      double ret = LandmarkDetectorPINVOKE.SVR_patch_expert_bias_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_cv__Mat_T_float_t weights {
    set {
      LandmarkDetectorPINVOKE.SVR_patch_expert_weights_set(swigCPtr, SWIGTYPE_p_cv__Mat_T_float_t.getCPtr(value));
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_cv__Mat_T_float_t ret = new SWIGTYPE_p_cv__Mat_T_float_t(LandmarkDetectorPINVOKE.SVR_patch_expert_weights_get(swigCPtr), true);
      if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public Int_DoubleMatMap weights_dfts {
    set {
      LandmarkDetectorPINVOKE.SVR_patch_expert_weights_dfts_set(swigCPtr, Int_DoubleMatMap.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = LandmarkDetectorPINVOKE.SVR_patch_expert_weights_dfts_get(swigCPtr);
      Int_DoubleMatMap ret = (cPtr == global::System.IntPtr.Zero) ? null : new Int_DoubleMatMap(cPtr, false);
      return ret;
    } 
  }

  public double confidence {
    set {
      LandmarkDetectorPINVOKE.SVR_patch_expert_confidence_set(swigCPtr, value);
    } 
    get {
      double ret = LandmarkDetectorPINVOKE.SVR_patch_expert_confidence_get(swigCPtr);
      return ret;
    } 
  }

  public SVR_patch_expert() : this(LandmarkDetectorPINVOKE.new_SVR_patch_expert__SWIG_0(), true) {
  }

  public SVR_patch_expert(SVR_patch_expert other) : this(LandmarkDetectorPINVOKE.new_SVR_patch_expert__SWIG_1(SVR_patch_expert.getCPtr(other)), true) {
    if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Read(SWIGTYPE_p_std__ifstream stream) {
    LandmarkDetectorPINVOKE.SVR_patch_expert_Read(swigCPtr, SWIGTYPE_p_std__ifstream.getCPtr(stream));
    if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Response(SWIGTYPE_p_cv__Mat_T_float_t area_of_interest, SWIGTYPE_p_cv__Mat_T_float_t response) {
    LandmarkDetectorPINVOKE.SVR_patch_expert_Response(swigCPtr, SWIGTYPE_p_cv__Mat_T_float_t.getCPtr(area_of_interest), SWIGTYPE_p_cv__Mat_T_float_t.getCPtr(response));
    if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

  public void ResponseDepth(SWIGTYPE_p_cv__Mat_T_float_t area_of_interest, SWIGTYPE_p_cv__Mat_T_float_t response) {
    LandmarkDetectorPINVOKE.SVR_patch_expert_ResponseDepth(swigCPtr, SWIGTYPE_p_cv__Mat_T_float_t.getCPtr(area_of_interest), SWIGTYPE_p_cv__Mat_T_float_t.getCPtr(response));
    if (LandmarkDetectorPINVOKE.SWIGPendingException.Pending) throw LandmarkDetectorPINVOKE.SWIGPendingException.Retrieve();
  }

}
